model_folder: "/gdrive/My Drive/Models/TsResnet18_SGDR/Embedder_256"
train_folder: "/gdrive/My Drive/Datasets/HAR_dataset_v1"
val_folder: "/gdrive/My Drive/Datasets/HAR_dataset_v1"
output_folder: "/gdrive/My Drive/Models/TsResnet18_SGDR/Classifiers/basefinetuned_256"
batch_size: 64
embedding_dim: 256
optim_file: "/gdrive/My Drive/Hyperparameter_opt/Metric_Learning_v1/SGDR/experiment.json"
pretrain: True
balanced: False
n_epochs: 50 
patience: 10
freeze: ()