model_folder: "/gdrive/My Drive/Models/TsResnet18_SGDR/Classifiers/basefrozentrunk_256"
batch_size: 64
embedding_dim: 256
train_folder: "/gdrive/My Drive/Datasets/HAR_dataset_v1"
val_folder: "/gdrive/My Drive/Datasets/HAR_dataset_v1"
results_folder: "/gdrive/My Drive/Results/Behaviours/basefrozentrunk_256"
calibration: True
base_folder:  "/gdrive/My Drive/Datasets/HAR_dataset_v1"
ActiveLearning: False 

