use_pretrained : True
save_dir: "/gdrive/My Drive/HAR_Video_Classification/ID3_SGDR_lr_0_005_pretrained"
logging_file: "/gdrive/My Drive/HAR_Video_Classification/ID3_SGDR_lr_0_005_pretrained/logging.txt"
model: 'i3d_resnet50_v1_custom'
eval: False
data_aug: "v1"
train_only: False
num_epochs: 50
resume_epoch: 0
lr: 0.005


