model_folder: "/gdrive/My Drive/Models/TsResnet18_SGDR/ActiveLearning/Classifiers/basefrozen_256_v1"
batch_size: 64
embedding_dim: 256
train_folder: "/gdrive/My Drive/Datasets/HAR_AL/HAR_dataset_AL_v1"
val_folder: "/gdrive/My Drive/Datasets/HAR_dataset_v1"
base_folder: "/gdrive/My Drive/Datasets/HAR_dataset_v1"
results_folder: "/gdrive/My Drive/Results/Behaviours/ActiveLearning/basefrozen_256_v1"
calibration: True
ActiveLearning: True

