model_folder: "/gdrive/My Drive/Models/TsResnet18_SGDR/ActiveLearning/Classifiers/basefrozen_balanced_256_v1"
train_folder: "/gdrive/My Drive/Datasets/HAR_AL/HAR_dataset_AL_v2"
val_folder: "/gdrive/My Drive/Datasets/HAR_dataset_v1"
base_folder: "/gdrive/My Drive/Datasets/HAR_dataset_v1"
output_folder: "/gdrive/My Drive/Models/TsResnet18_SGDR/ActiveLearning/Classifiers/basefrozen_balanced_256_v2"
batch_size: 64
embedding_dim: 256
optim_file: "/gdrive/My Drive/Hyperparameter_opt/Metric_Learning_v1/SGDR/experiment.json"
pretrain: True
balanced: True
n_epochs: 20 
patience: 20
freeze: ["trunk","embedder"]
ActiveLearning: True